name: Test Team Notifications

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch to create requirements PR against"
        required: true
        default: 'master'

jobs:
  test_team_notification:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: setup target branch
        run: echo "target_branch=$(if ['${{ github.event.inputs.branch }}' = '']; then echo 'master'; else echo '${{ github.event.inputs.branch }}'; fi)" >> $GITHUB_ENV

      - name: check out the repo
        uses: actions/checkout@v1
        with:
          ref: ${{ env.target_branch }}
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: make upgrade
        run: |
          cd $GITHUB_WORKSPACE
          echo "One more line" >> README.rst

      - name: setup testeng-ci
        run: |
          git clone https://github.com/edx/testeng-ci.git
          cd $GITHUB_WORKSPACE/testeng-ci
          pip install -r requirements/base.txt

      - name: create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
          GITHUB_USER_EMAIL: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
        run: |  
          cd $GITHUB_WORKSPACE/testeng-ci
          python -m jenkins.pull_request_creator --repo-root=$GITHUB_WORKSPACE \
          --target-branch="${{ env.target_branch }}" --base-branch-name="test-team-notifications" \
          --commit-message="temp: Testing notifications" --pr-title="temp: Testing notifications" \
          --pr-body="JUST TESTING." \
          --user-reviewers="" --team-reviewers="community-engineering" --delete-old-pull-requests
